repos:
- repo: local
  hooks:
  - id: ruff-fix
    name: ruff fix
    entry: uv run ruff check --fix
    language: python
    types: [python]
    files: src/.*\.py$|tests/.*\.py$
  - id: isort
    name: isort
    entry: uv run isort
    language: python
    types: [python]
    files: src/.*\.py$|tests/.*\.py$
  - id: black
    name: black
    entry: uv run black
    language: python
    types: [python]
    files: src/.*\.py$|tests/.*\.py$