repos:
	- repo: local
    hooks:
    - id: ruff-fix
      name: ruff fix
      entry: uv run ruff check src tests --fix
      language: python
      types: [python]
      files: \.py$
    - id: isort
      name: isort
      entry: uv run isort src tests
      language: python
      types: [python]
      files: \.py$
    - id: black
      name: black
      entry: uv run black src tests
      language: python
      types: [python]
      files: \.py$