[package]
name = "respfuzzer"
version = "0.1.0"
edition = "2021"

[lib]
name = "mutate"
# "cdylib" is necessary to produce a shared library for Python to import from.
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.2", features = ["extension-module"] }