[model_config]
base_url = "http://192.168.2.29:8000/v1"
api_key = "none"
model_name = "qwen3-32b-awq"

[db_config]
db_name = "tracefuzz-judger-budget10-new-prompt" # without .db suffix

[redis]
host = "127.0.0.1"
port = 6379
db = 0

[fuzz]
execution_timeout = 5.0
mutants_per_seed = 100
max_try_per_seed = 10

[reflective_seeder]
api_key = "none"
# base_url = "http://192.168.2.29:8000/v1"
# model_name = "qwen3-32b-awq"
base_url = "http://192.168.3.15:4399/v1"
model_name = "qwen3-coder-30b-a3b"
concurrency = 12

[fuzz4all]
api_key = "none"
base_url = "http://192.168.3.15:4399/v1"
model_name = "qwen3-coder-30b-a3b"
strategy = 1