[model_config]
base_url = "http://192.168.2.29:8000/v1"
api_key = "none"
model_name = "qwen3-32b-awq"

[db_config]
db_name = "tracefuzz-judger-budget10.db"

[redis]
host = "127.0.0.1"
port = 6379
db = 0

[fuzz]
execution_timeout = 5.0
mutants_per_seed = 1000

[reflective_seeder]
api_key = "none"
# base_url = "http://192.168.2.29:8000/v1"
# model_name = "qwen3-32b-awq"
base_url = "http://192.168.1.44:8022/v1"
model_name = "qwen3-coder-30b-a3b"