[llm]
base_url = "http://192.168.2.29:8021/v1"
api_key = "none"
model_name = "qwen3-30b-a3b"

[db_config]
db_name = "tracefuzz-20251013" # without .db suffix

[redis]
host = "127.0.0.1"
port = 6379
db = 0

[fuzz]
execution_timeout = 5.0
mutants_per_seed = 100
max_try_per_seed = 10

[reflective_seeder]
concurrency = 12

[fuzz4all]
strategy = 1