[model_config]
base_url = "http://192.168.2.29:8000/v1"
api_key = "none"
model_name = "qwen3-32b-awq"

[db_config]
db_name = "tracefuzz-big"

[redis]
host = "127.0.0.1"
port = 6379
db = 0

[fuzz]
execution_timeout = 5.0
mutants_per_seed = 1000

[reflective_seeder]
base_url = "http://192.168.2.29:8000/v1"
api_key = "none"
model_name = "qwen3-32b-awq"