[build-system]
requires = ["setuptools", "Cython"]
build-backend = "setuptools.build_meta"

[project]
name = "mplfuzz"
version = "0.1.0"
description = "Fuzz Python Libraries as MCP services"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fire>=0.7.1",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "openai>=1.109.1",
    "pydantic>=2.11.9",
    "redis>=6.4.0",
    "sqlite-web>=0.6.4",
]

[project.optional-dependencies]
dev = [
    "black>=25.9.0",
    "isort>=6.0.1",
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
]

[tool.pytest.ini_options]

addopts = "--cov=src --cov-report=html"

# 改变用例的查找路径规则，当前目录的testcase文件夹
testpaths = ["tests"]

# 模块名的规则，配置测试搜索的模块文件名称
python_files = ["test_*.py"]

# 类名的规则，配置测试搜索的测试类名
python_classes = ["Test*"]

# 方法名的规则，配置测试搜索的测试函数名
python_functions = ["test_*"]

[tool.black]
line-length = 122
target-version = ["py313"]
include = '\.pyi?$'

[tool.isort]
profile = "black"

[[tool.uv.index]]
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
default = true


[project.scripts]
library_visitor = "mplfuzz.library_visitor:main"
agentic_api_resolver = "mplfuzz.agentic_api_resolver:main"
fuzz_library = "mplfuzz.fuzz.fuzz_library:main"
db_tools = "mplfuzz.utils.db_tools:main"
